### ISSUE TITLE
BEL citation and evidence management

### ISSUE THREAD

**Issue by Cojabi** [bio2bel/hmdb#4]
For protein-metabolite association no reference articles (so also no evidence) is given.
So we lack provenance and can only refer to "but its in the database"

**Comment by cthoyt** [comment]
Aww... I guess we'll have to suck it up

**Comment by aramgrigoryan** [comment]
contact the guys there

**Comment by cthoyt** [comment]
Solution is to leave placeholder evidence that just mentions that it came from HMDB
